//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/Other/Configuration/CharacterActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CharacterActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CharacterActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CharacterActions"",
    ""maps"": [
        {
            ""name"": ""CharacterInputs"",
            ""id"": ""669fdfc8-ae27-4c72-b575-9d9427919c61"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""a14f75c3-fb57-4178-9057-67590cec7d69"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""Value"",
                    ""id"": ""4095f93b-a587-4939-aa8a-2cdd0031706e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""PrincipalAttack"",
                    ""type"": ""Button"",
                    ""id"": ""817295e4-4167-41b8-80c2-448ae4755ee1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LaunchPrincipalWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""841c5da2-4d5b-4a00-9488-68908e9db805"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LaunchSecondaryWeapon"",
                    ""type"": ""Button"",
                    ""id"": ""dcd6104b-6bc0-4d41-b69d-d8e2457c967c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""b2fc08e8-a649-4b83-946f-1df9b26a4903"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableSecondaryAction"",
                    ""type"": ""Button"",
                    ""id"": ""e64bb2ca-faa6-4dc7-bd1f-86ab18dc6153"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""c260306e-a6b5-4492-9f6f-c6572072b6d1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeSkillUp"",
                    ""type"": ""Button"",
                    ""id"": ""3465deb2-37df-43e6-89e3-934c94e6a28f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeSkillDown"",
                    ""type"": ""Button"",
                    ""id"": ""8e419c73-c6c4-4afc-9b29-8eab9f617a2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObjectUp"",
                    ""type"": ""Button"",
                    ""id"": ""d5e3393a-294e-4b05-bc7a-466ee12ee77b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObjectDown"",
                    ""type"": ""Button"",
                    ""id"": ""c4436d29-f26b-4666-aa47-ca7d26c861e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObjectForTake"",
                    ""type"": ""Value"",
                    ""id"": ""45fa18f5-81e6-456c-a43a-66d1885de12c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ChangeObject1"",
                    ""type"": ""Button"",
                    ""id"": ""82c0470a-c114-4f00-8d20-98702758c47f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObject2"",
                    ""type"": ""Button"",
                    ""id"": ""74b49586-5dd0-46fd-9e7e-6f4030002c3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObject3"",
                    ""type"": ""Button"",
                    ""id"": ""87b29e86-6b1d-4eae-8daf-7381563cb7bb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObject4"",
                    ""type"": ""Button"",
                    ""id"": ""767b56a1-5939-4916-9d92-de7ef8deda9c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObject5"",
                    ""type"": ""Button"",
                    ""id"": ""2e39d5f3-3ed3-4424-8606-0c6007e4c556"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeObject6"",
                    ""type"": ""Button"",
                    ""id"": ""605c5579-bc19-40de-ba6a-18259226ab80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseSkill"",
                    ""type"": ""Button"",
                    ""id"": ""bfc1cc80-0473-4013-9910-021b3647e148"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseObject"",
                    ""type"": ""Button"",
                    ""id"": ""d1c17128-89e8-47cb-805e-8dc7f1011a33"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenInventory"",
                    ""type"": ""Button"",
                    ""id"": ""9ca8eb10-75a3-4490-8ef9-dd17d9ac7f7e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LookEnemy"",
                    ""type"": ""Button"",
                    ""id"": ""c8901698-1874-4450-87c4-9c2a5d211cae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePos"",
                    ""type"": ""Value"",
                    ""id"": ""b4bfae70-c59c-4f43-a050-634a7d8e64ab"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""6f448dc1-bccd-4995-8317-78b4f89313a9"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnlockCamera"",
                    ""type"": ""Button"",
                    ""id"": ""8fb2c31e-f13e-4f70-b888-fc9df1ff485f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""f59b8d91-6e1a-468d-8dcb-58572365110b"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""18fbd7ed-84ae-41b4-bf8a-96e2e07fcf72"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""79091fe7-cf0c-4d44-b35e-d85f34ceaf40"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""587c8d0f-782d-4d8e-b44d-cdad0cfcc8cc"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""eae3f1a4-7d0d-46a0-9b6d-13b7904deb2d"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""12879c56-68b1-40ca-a2e4-033dc0120353"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c189073-94d2-4079-9810-feb300959554"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""814a2455-6d82-4b44-81e7-19a79c439852"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""706048ba-2102-4efd-9325-2ef8a1278371"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d64afe4-82aa-475f-98a7-d8913003c4d3"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""926bdd6d-99b6-46e0-b96e-3655b37a20a0"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableSecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6384a7b-e452-49da-bc7e-38780e730325"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableSecondaryAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98b65b27-ed1a-404f-a20e-986efdc668b6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrincipalAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84b6bb96-5201-4fc3-91c5-3b949eab2827"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrincipalAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b72083a5-3919-456d-b070-9c5046437743"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaunchPrincipalWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6a7bbd62-51c5-4113-9059-c164b1450b88"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaunchPrincipalWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e79e0ee0-34d2-4a16-9bf0-ac3f7e2134bb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaunchSecondaryWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d27d2748-1865-47d9-8405-ca64b3945666"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LaunchSecondaryWeapon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acc71e18-9fcd-45fd-8dea-c139655340ce"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSkillUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""59e0b2d7-a7aa-4a85-9e12-353edd17be32"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSkillUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4736bce7-d4a1-460d-8871-09f3c45ef88a"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObject1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d78eba4-3795-46cc-82f7-886c25421037"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObject2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b3b73dc-39d3-48a6-85a0-a23df9cf5cec"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObject3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c11259c4-4a55-4652-bfe5-52b86ff13285"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObject4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""798d9385-c50c-4f25-ba7c-28e7c13aaedb"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObject5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba2fa0be-22d3-4917-af75-e6f4d4dc3669"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObject6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98f14e8e-cded-4e0b-8269-0495c96dbfa9"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1274b64a-eb4f-4f74-9230-6f50946fc328"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseSkill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""930ad1b4-ccd8-4801-8179-befabf4e968d"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c365b7b6-0a88-4c4d-95bb-ee4a07f2704e"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseObject"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b047809-3cc9-4c20-913c-b7dc0217599f"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b385ecb7-b4e2-43a1-8cf1-ac269177756d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4397ac04-b39e-4ca9-9cb7-cd1b88a47497"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookEnemy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c2d6a87-a32b-42f1-9ccc-28b8a1840061"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookEnemy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""162b06a8-331f-4ebc-abf8-38bae434b440"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObjectUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edf1307b-2f4e-4788-9808-72956fbb25de"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObjectDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f0a2a9f-2e53-4328-9f1d-d34ba444d76c"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSkillDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c57567d4-54e4-4abd-9ea9-9b5b5c885064"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeSkillDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3802f7f-0fcb-4719-a290-41048d06c72e"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObjectForTake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8b7c99fa-2ca8-4ac8-a4c3-6f8e95d674a5"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeObjectForTake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4fb371eb-3038-4ab5-afd3-98f68d3fd851"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0271058a-1b5b-4e17-8fd7-f33e226260d2"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9ed8459-a239-4348-8681-750c97ddb263"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8b70043-10f5-458e-b7db-638f9c99d409"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e511dac-fda4-477c-8a2d-bfad10087300"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33aae84e-aec9-4bc8-bc1b-d01f08a308ed"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnlockCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be0b6ffe-2bb6-402e-9e2f-5d1ad63767ad"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnlockCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterInputs
        m_CharacterInputs = asset.FindActionMap("CharacterInputs", throwIfNotFound: true);
        m_CharacterInputs_Movement = m_CharacterInputs.FindAction("Movement", throwIfNotFound: true);
        m_CharacterInputs_MoveCamera = m_CharacterInputs.FindAction("MoveCamera", throwIfNotFound: true);
        m_CharacterInputs_PrincipalAttack = m_CharacterInputs.FindAction("PrincipalAttack", throwIfNotFound: true);
        m_CharacterInputs_LaunchPrincipalWeapon = m_CharacterInputs.FindAction("LaunchPrincipalWeapon", throwIfNotFound: true);
        m_CharacterInputs_LaunchSecondaryWeapon = m_CharacterInputs.FindAction("LaunchSecondaryWeapon", throwIfNotFound: true);
        m_CharacterInputs_Interact = m_CharacterInputs.FindAction("Interact", throwIfNotFound: true);
        m_CharacterInputs_EnableSecondaryAction = m_CharacterInputs.FindAction("EnableSecondaryAction", throwIfNotFound: true);
        m_CharacterInputs_Jump = m_CharacterInputs.FindAction("Jump", throwIfNotFound: true);
        m_CharacterInputs_ChangeSkillUp = m_CharacterInputs.FindAction("ChangeSkillUp", throwIfNotFound: true);
        m_CharacterInputs_ChangeSkillDown = m_CharacterInputs.FindAction("ChangeSkillDown", throwIfNotFound: true);
        m_CharacterInputs_ChangeObjectUp = m_CharacterInputs.FindAction("ChangeObjectUp", throwIfNotFound: true);
        m_CharacterInputs_ChangeObjectDown = m_CharacterInputs.FindAction("ChangeObjectDown", throwIfNotFound: true);
        m_CharacterInputs_ChangeObjectForTake = m_CharacterInputs.FindAction("ChangeObjectForTake", throwIfNotFound: true);
        m_CharacterInputs_ChangeObject1 = m_CharacterInputs.FindAction("ChangeObject1", throwIfNotFound: true);
        m_CharacterInputs_ChangeObject2 = m_CharacterInputs.FindAction("ChangeObject2", throwIfNotFound: true);
        m_CharacterInputs_ChangeObject3 = m_CharacterInputs.FindAction("ChangeObject3", throwIfNotFound: true);
        m_CharacterInputs_ChangeObject4 = m_CharacterInputs.FindAction("ChangeObject4", throwIfNotFound: true);
        m_CharacterInputs_ChangeObject5 = m_CharacterInputs.FindAction("ChangeObject5", throwIfNotFound: true);
        m_CharacterInputs_ChangeObject6 = m_CharacterInputs.FindAction("ChangeObject6", throwIfNotFound: true);
        m_CharacterInputs_UseSkill = m_CharacterInputs.FindAction("UseSkill", throwIfNotFound: true);
        m_CharacterInputs_UseObject = m_CharacterInputs.FindAction("UseObject", throwIfNotFound: true);
        m_CharacterInputs_OpenInventory = m_CharacterInputs.FindAction("OpenInventory", throwIfNotFound: true);
        m_CharacterInputs_LookEnemy = m_CharacterInputs.FindAction("LookEnemy", throwIfNotFound: true);
        m_CharacterInputs_MousePos = m_CharacterInputs.FindAction("MousePos", throwIfNotFound: true);
        m_CharacterInputs_Pause = m_CharacterInputs.FindAction("Pause", throwIfNotFound: true);
        m_CharacterInputs_UnlockCamera = m_CharacterInputs.FindAction("UnlockCamera", throwIfNotFound: true);
    }

    ~@CharacterActions()
    {
        UnityEngine.Debug.Assert(!m_CharacterInputs.enabled, "This will cause a leak and performance issues, CharacterActions.CharacterInputs.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterInputs
    private readonly InputActionMap m_CharacterInputs;
    private List<ICharacterInputsActions> m_CharacterInputsActionsCallbackInterfaces = new List<ICharacterInputsActions>();
    private readonly InputAction m_CharacterInputs_Movement;
    private readonly InputAction m_CharacterInputs_MoveCamera;
    private readonly InputAction m_CharacterInputs_PrincipalAttack;
    private readonly InputAction m_CharacterInputs_LaunchPrincipalWeapon;
    private readonly InputAction m_CharacterInputs_LaunchSecondaryWeapon;
    private readonly InputAction m_CharacterInputs_Interact;
    private readonly InputAction m_CharacterInputs_EnableSecondaryAction;
    private readonly InputAction m_CharacterInputs_Jump;
    private readonly InputAction m_CharacterInputs_ChangeSkillUp;
    private readonly InputAction m_CharacterInputs_ChangeSkillDown;
    private readonly InputAction m_CharacterInputs_ChangeObjectUp;
    private readonly InputAction m_CharacterInputs_ChangeObjectDown;
    private readonly InputAction m_CharacterInputs_ChangeObjectForTake;
    private readonly InputAction m_CharacterInputs_ChangeObject1;
    private readonly InputAction m_CharacterInputs_ChangeObject2;
    private readonly InputAction m_CharacterInputs_ChangeObject3;
    private readonly InputAction m_CharacterInputs_ChangeObject4;
    private readonly InputAction m_CharacterInputs_ChangeObject5;
    private readonly InputAction m_CharacterInputs_ChangeObject6;
    private readonly InputAction m_CharacterInputs_UseSkill;
    private readonly InputAction m_CharacterInputs_UseObject;
    private readonly InputAction m_CharacterInputs_OpenInventory;
    private readonly InputAction m_CharacterInputs_LookEnemy;
    private readonly InputAction m_CharacterInputs_MousePos;
    private readonly InputAction m_CharacterInputs_Pause;
    private readonly InputAction m_CharacterInputs_UnlockCamera;
    public struct CharacterInputsActions
    {
        private @CharacterActions m_Wrapper;
        public CharacterInputsActions(@CharacterActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_CharacterInputs_Movement;
        public InputAction @MoveCamera => m_Wrapper.m_CharacterInputs_MoveCamera;
        public InputAction @PrincipalAttack => m_Wrapper.m_CharacterInputs_PrincipalAttack;
        public InputAction @LaunchPrincipalWeapon => m_Wrapper.m_CharacterInputs_LaunchPrincipalWeapon;
        public InputAction @LaunchSecondaryWeapon => m_Wrapper.m_CharacterInputs_LaunchSecondaryWeapon;
        public InputAction @Interact => m_Wrapper.m_CharacterInputs_Interact;
        public InputAction @EnableSecondaryAction => m_Wrapper.m_CharacterInputs_EnableSecondaryAction;
        public InputAction @Jump => m_Wrapper.m_CharacterInputs_Jump;
        public InputAction @ChangeSkillUp => m_Wrapper.m_CharacterInputs_ChangeSkillUp;
        public InputAction @ChangeSkillDown => m_Wrapper.m_CharacterInputs_ChangeSkillDown;
        public InputAction @ChangeObjectUp => m_Wrapper.m_CharacterInputs_ChangeObjectUp;
        public InputAction @ChangeObjectDown => m_Wrapper.m_CharacterInputs_ChangeObjectDown;
        public InputAction @ChangeObjectForTake => m_Wrapper.m_CharacterInputs_ChangeObjectForTake;
        public InputAction @ChangeObject1 => m_Wrapper.m_CharacterInputs_ChangeObject1;
        public InputAction @ChangeObject2 => m_Wrapper.m_CharacterInputs_ChangeObject2;
        public InputAction @ChangeObject3 => m_Wrapper.m_CharacterInputs_ChangeObject3;
        public InputAction @ChangeObject4 => m_Wrapper.m_CharacterInputs_ChangeObject4;
        public InputAction @ChangeObject5 => m_Wrapper.m_CharacterInputs_ChangeObject5;
        public InputAction @ChangeObject6 => m_Wrapper.m_CharacterInputs_ChangeObject6;
        public InputAction @UseSkill => m_Wrapper.m_CharacterInputs_UseSkill;
        public InputAction @UseObject => m_Wrapper.m_CharacterInputs_UseObject;
        public InputAction @OpenInventory => m_Wrapper.m_CharacterInputs_OpenInventory;
        public InputAction @LookEnemy => m_Wrapper.m_CharacterInputs_LookEnemy;
        public InputAction @MousePos => m_Wrapper.m_CharacterInputs_MousePos;
        public InputAction @Pause => m_Wrapper.m_CharacterInputs_Pause;
        public InputAction @UnlockCamera => m_Wrapper.m_CharacterInputs_UnlockCamera;
        public InputActionMap Get() { return m_Wrapper.m_CharacterInputs; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterInputsActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterInputsActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterInputsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterInputsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @MoveCamera.started += instance.OnMoveCamera;
            @MoveCamera.performed += instance.OnMoveCamera;
            @MoveCamera.canceled += instance.OnMoveCamera;
            @PrincipalAttack.started += instance.OnPrincipalAttack;
            @PrincipalAttack.performed += instance.OnPrincipalAttack;
            @PrincipalAttack.canceled += instance.OnPrincipalAttack;
            @LaunchPrincipalWeapon.started += instance.OnLaunchPrincipalWeapon;
            @LaunchPrincipalWeapon.performed += instance.OnLaunchPrincipalWeapon;
            @LaunchPrincipalWeapon.canceled += instance.OnLaunchPrincipalWeapon;
            @LaunchSecondaryWeapon.started += instance.OnLaunchSecondaryWeapon;
            @LaunchSecondaryWeapon.performed += instance.OnLaunchSecondaryWeapon;
            @LaunchSecondaryWeapon.canceled += instance.OnLaunchSecondaryWeapon;
            @Interact.started += instance.OnInteract;
            @Interact.performed += instance.OnInteract;
            @Interact.canceled += instance.OnInteract;
            @EnableSecondaryAction.started += instance.OnEnableSecondaryAction;
            @EnableSecondaryAction.performed += instance.OnEnableSecondaryAction;
            @EnableSecondaryAction.canceled += instance.OnEnableSecondaryAction;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @ChangeSkillUp.started += instance.OnChangeSkillUp;
            @ChangeSkillUp.performed += instance.OnChangeSkillUp;
            @ChangeSkillUp.canceled += instance.OnChangeSkillUp;
            @ChangeSkillDown.started += instance.OnChangeSkillDown;
            @ChangeSkillDown.performed += instance.OnChangeSkillDown;
            @ChangeSkillDown.canceled += instance.OnChangeSkillDown;
            @ChangeObjectUp.started += instance.OnChangeObjectUp;
            @ChangeObjectUp.performed += instance.OnChangeObjectUp;
            @ChangeObjectUp.canceled += instance.OnChangeObjectUp;
            @ChangeObjectDown.started += instance.OnChangeObjectDown;
            @ChangeObjectDown.performed += instance.OnChangeObjectDown;
            @ChangeObjectDown.canceled += instance.OnChangeObjectDown;
            @ChangeObjectForTake.started += instance.OnChangeObjectForTake;
            @ChangeObjectForTake.performed += instance.OnChangeObjectForTake;
            @ChangeObjectForTake.canceled += instance.OnChangeObjectForTake;
            @ChangeObject1.started += instance.OnChangeObject1;
            @ChangeObject1.performed += instance.OnChangeObject1;
            @ChangeObject1.canceled += instance.OnChangeObject1;
            @ChangeObject2.started += instance.OnChangeObject2;
            @ChangeObject2.performed += instance.OnChangeObject2;
            @ChangeObject2.canceled += instance.OnChangeObject2;
            @ChangeObject3.started += instance.OnChangeObject3;
            @ChangeObject3.performed += instance.OnChangeObject3;
            @ChangeObject3.canceled += instance.OnChangeObject3;
            @ChangeObject4.started += instance.OnChangeObject4;
            @ChangeObject4.performed += instance.OnChangeObject4;
            @ChangeObject4.canceled += instance.OnChangeObject4;
            @ChangeObject5.started += instance.OnChangeObject5;
            @ChangeObject5.performed += instance.OnChangeObject5;
            @ChangeObject5.canceled += instance.OnChangeObject5;
            @ChangeObject6.started += instance.OnChangeObject6;
            @ChangeObject6.performed += instance.OnChangeObject6;
            @ChangeObject6.canceled += instance.OnChangeObject6;
            @UseSkill.started += instance.OnUseSkill;
            @UseSkill.performed += instance.OnUseSkill;
            @UseSkill.canceled += instance.OnUseSkill;
            @UseObject.started += instance.OnUseObject;
            @UseObject.performed += instance.OnUseObject;
            @UseObject.canceled += instance.OnUseObject;
            @OpenInventory.started += instance.OnOpenInventory;
            @OpenInventory.performed += instance.OnOpenInventory;
            @OpenInventory.canceled += instance.OnOpenInventory;
            @LookEnemy.started += instance.OnLookEnemy;
            @LookEnemy.performed += instance.OnLookEnemy;
            @LookEnemy.canceled += instance.OnLookEnemy;
            @MousePos.started += instance.OnMousePos;
            @MousePos.performed += instance.OnMousePos;
            @MousePos.canceled += instance.OnMousePos;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @UnlockCamera.started += instance.OnUnlockCamera;
            @UnlockCamera.performed += instance.OnUnlockCamera;
            @UnlockCamera.canceled += instance.OnUnlockCamera;
        }

        private void UnregisterCallbacks(ICharacterInputsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @MoveCamera.started -= instance.OnMoveCamera;
            @MoveCamera.performed -= instance.OnMoveCamera;
            @MoveCamera.canceled -= instance.OnMoveCamera;
            @PrincipalAttack.started -= instance.OnPrincipalAttack;
            @PrincipalAttack.performed -= instance.OnPrincipalAttack;
            @PrincipalAttack.canceled -= instance.OnPrincipalAttack;
            @LaunchPrincipalWeapon.started -= instance.OnLaunchPrincipalWeapon;
            @LaunchPrincipalWeapon.performed -= instance.OnLaunchPrincipalWeapon;
            @LaunchPrincipalWeapon.canceled -= instance.OnLaunchPrincipalWeapon;
            @LaunchSecondaryWeapon.started -= instance.OnLaunchSecondaryWeapon;
            @LaunchSecondaryWeapon.performed -= instance.OnLaunchSecondaryWeapon;
            @LaunchSecondaryWeapon.canceled -= instance.OnLaunchSecondaryWeapon;
            @Interact.started -= instance.OnInteract;
            @Interact.performed -= instance.OnInteract;
            @Interact.canceled -= instance.OnInteract;
            @EnableSecondaryAction.started -= instance.OnEnableSecondaryAction;
            @EnableSecondaryAction.performed -= instance.OnEnableSecondaryAction;
            @EnableSecondaryAction.canceled -= instance.OnEnableSecondaryAction;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @ChangeSkillUp.started -= instance.OnChangeSkillUp;
            @ChangeSkillUp.performed -= instance.OnChangeSkillUp;
            @ChangeSkillUp.canceled -= instance.OnChangeSkillUp;
            @ChangeSkillDown.started -= instance.OnChangeSkillDown;
            @ChangeSkillDown.performed -= instance.OnChangeSkillDown;
            @ChangeSkillDown.canceled -= instance.OnChangeSkillDown;
            @ChangeObjectUp.started -= instance.OnChangeObjectUp;
            @ChangeObjectUp.performed -= instance.OnChangeObjectUp;
            @ChangeObjectUp.canceled -= instance.OnChangeObjectUp;
            @ChangeObjectDown.started -= instance.OnChangeObjectDown;
            @ChangeObjectDown.performed -= instance.OnChangeObjectDown;
            @ChangeObjectDown.canceled -= instance.OnChangeObjectDown;
            @ChangeObjectForTake.started -= instance.OnChangeObjectForTake;
            @ChangeObjectForTake.performed -= instance.OnChangeObjectForTake;
            @ChangeObjectForTake.canceled -= instance.OnChangeObjectForTake;
            @ChangeObject1.started -= instance.OnChangeObject1;
            @ChangeObject1.performed -= instance.OnChangeObject1;
            @ChangeObject1.canceled -= instance.OnChangeObject1;
            @ChangeObject2.started -= instance.OnChangeObject2;
            @ChangeObject2.performed -= instance.OnChangeObject2;
            @ChangeObject2.canceled -= instance.OnChangeObject2;
            @ChangeObject3.started -= instance.OnChangeObject3;
            @ChangeObject3.performed -= instance.OnChangeObject3;
            @ChangeObject3.canceled -= instance.OnChangeObject3;
            @ChangeObject4.started -= instance.OnChangeObject4;
            @ChangeObject4.performed -= instance.OnChangeObject4;
            @ChangeObject4.canceled -= instance.OnChangeObject4;
            @ChangeObject5.started -= instance.OnChangeObject5;
            @ChangeObject5.performed -= instance.OnChangeObject5;
            @ChangeObject5.canceled -= instance.OnChangeObject5;
            @ChangeObject6.started -= instance.OnChangeObject6;
            @ChangeObject6.performed -= instance.OnChangeObject6;
            @ChangeObject6.canceled -= instance.OnChangeObject6;
            @UseSkill.started -= instance.OnUseSkill;
            @UseSkill.performed -= instance.OnUseSkill;
            @UseSkill.canceled -= instance.OnUseSkill;
            @UseObject.started -= instance.OnUseObject;
            @UseObject.performed -= instance.OnUseObject;
            @UseObject.canceled -= instance.OnUseObject;
            @OpenInventory.started -= instance.OnOpenInventory;
            @OpenInventory.performed -= instance.OnOpenInventory;
            @OpenInventory.canceled -= instance.OnOpenInventory;
            @LookEnemy.started -= instance.OnLookEnemy;
            @LookEnemy.performed -= instance.OnLookEnemy;
            @LookEnemy.canceled -= instance.OnLookEnemy;
            @MousePos.started -= instance.OnMousePos;
            @MousePos.performed -= instance.OnMousePos;
            @MousePos.canceled -= instance.OnMousePos;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @UnlockCamera.started -= instance.OnUnlockCamera;
            @UnlockCamera.performed -= instance.OnUnlockCamera;
            @UnlockCamera.canceled -= instance.OnUnlockCamera;
        }

        public void RemoveCallbacks(ICharacterInputsActions instance)
        {
            if (m_Wrapper.m_CharacterInputsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterInputsActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterInputsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterInputsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterInputsActions @CharacterInputs => new CharacterInputsActions(this);
    public interface ICharacterInputsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnMoveCamera(InputAction.CallbackContext context);
        void OnPrincipalAttack(InputAction.CallbackContext context);
        void OnLaunchPrincipalWeapon(InputAction.CallbackContext context);
        void OnLaunchSecondaryWeapon(InputAction.CallbackContext context);
        void OnInteract(InputAction.CallbackContext context);
        void OnEnableSecondaryAction(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnChangeSkillUp(InputAction.CallbackContext context);
        void OnChangeSkillDown(InputAction.CallbackContext context);
        void OnChangeObjectUp(InputAction.CallbackContext context);
        void OnChangeObjectDown(InputAction.CallbackContext context);
        void OnChangeObjectForTake(InputAction.CallbackContext context);
        void OnChangeObject1(InputAction.CallbackContext context);
        void OnChangeObject2(InputAction.CallbackContext context);
        void OnChangeObject3(InputAction.CallbackContext context);
        void OnChangeObject4(InputAction.CallbackContext context);
        void OnChangeObject5(InputAction.CallbackContext context);
        void OnChangeObject6(InputAction.CallbackContext context);
        void OnUseSkill(InputAction.CallbackContext context);
        void OnUseObject(InputAction.CallbackContext context);
        void OnOpenInventory(InputAction.CallbackContext context);
        void OnLookEnemy(InputAction.CallbackContext context);
        void OnMousePos(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnUnlockCamera(InputAction.CallbackContext context);
    }
}
